### PR TITLE
Remove annotation that fixes gitea address

### PR DESCRIPTION
**Pull request by liamfallon**
What type of PR is this?

    Uncomment only one  /kind <> line, hit enter to put that in a new line, and remove leading whitespaces from that line:

/kind bug

    /kind cleanup
    /kind design
    /kind documentation
    /kind failing-test
    /kind feature
    /kind flake

What this PR does / why we need it:
The current gitea package will not install if the installation environment does not use an address range with the address  172.18.0.200 in it. This PR removes the annotation that insists on a fixed IP address for the Gitea service.

Which issue(s) this PR fixes:

Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?:

### CODE REVIEW

**Comment by liamfallon** [comment]
@electrocucaracha I don't think this will break the sandbox install and it makes the package more useful.

**Comment by electrocucaracha** [comment]
> @electrocucaracha I don't think this will break the sandbox install and it makes the package more useful.

I don't think that it breaks something in the sandbox neither, but it's quite useful during the troubleshooting and/or demos given that facilitates the port forwarding process with MetalLB services.

**Comment by johnbelamaric** [comment]
Note that this package is in the "distros/sandbox" directory. Thus, it intentionally includes opinionated, sandbox-specific configuration. I would rather see a way to parameterize the metal-lb network, if this is an issue and we need  to enable the sandbox to have different networks - but since it's a sandbox, why would we need this?

Plus, we absolutely need gitea exposed via metal-lb for configsync to access it from workload clusters.

**Comment by johnbelamaric** [comment]
In other words, I think this will break the sandbox, because without this we need DNS for Gitea access from workload clusters, which I don't think we have.

**Comment by liamfallon** [comment]
That's fine John and Victor. I'll abandon the PR. We can probably manage changing the annotation using a kpt function in other installations.

**Comment by johnbelamaric** [comment]
> That's fine John and Victor. I'll abandon the PR. We can probably manage changing the annotation using a kpt function in other installations.

Another option is to move a "clean" gitea package into nephio/optional, then clone and modify that into the sandbox directory, just adding this annotation.

In general, we need to choose the right way to mutate packages for the circumstances:
 - Manually clone and edit. This creates a "derivative" package. For example, in this case we would have an upstream gitea package, clone it into the sandbox repo and add the sandbox specifics. Updates to the upstream can be discovered through kpt/porchctl or through the Nephio UI, and are manually applied. The derivative package could be a "blueprint" like this, or a deployment for a specific cluster. Edits can be done via any tool (kpt function, text editor, sed/awk/etc).
 - Automated clone and edit via PackageVariant. Programatically edit and mutate the package. Updates are proposed automatically by the controller when the upstream changes. Edits can be done via controllers regulated through package conditions, or manually via porchctl pull, edit with kpt function, text, editsor, sed/awk/etc, porchctl push.

**Comment by liamfallon** [comment]
> > That's fine John and Victor. I'll abandon the PR. We can probably manage changing the annotation using a kpt function in other installations.
> 
> Another option is to move a "clean" gitea package into nephio/optional, then clone and modify that into the sandbox directory, just adding this annotation.
> 
> In general, we need to choose the right way to mutate packages for the circumstances:
> 
>     * Manually clone and edit. This creates a "derivative" package. For example, in this case we would have an upstream gitea package, clone it into the sandbox repo and add the sandbox specifics. Updates to the upstream can be discovered through kpt/porchctl or through the Nephio UI, and are manually applied. The derivative package could be a "blueprint" like this, or a deployment for a specific cluster. Edits can be done via any tool (kpt function, text editor, sed/awk/etc).
> 
>     * Automated clone and edit via PackageVariant. Programatically edit and mutate the package. Updates are proposed automatically by the controller when the upstream changes. Edits can be done via controllers regulated through package conditions, or manually via porchctl pull, edit with kpt function, text, editsor, sed/awk/etc, porchctl push.

I was actually just thinking about this. A kpt function or a PackageVariant would make perfect sense. We also have this situation in other packages where IP addresses and other config information is currently hardcoded and should be configurable.

**Pull request closed without merging**
