### PR TITLE
Fix free5gc-operator-role RBAC

### PR DESCRIPTION
**Pull request by lapentad**
WIP 
1. Updated [nfdeploy-fn](https://hub.docker.com/r/nephio/nfdeploy-fn/tags) docker image
2. Added Roles for _nfdeployments_ and _nfconfigs_
3. Adjusted privileges

### CODE REVIEW

**Comment by electrocucaracha** [comment]
@lapentad do we need to include the NFDeployment and NFConfig CRDs?

**Comment by lapentad** [comment]
I Removed them now

**Pull request merged**
