### PR TITLE
Directory structure for Nephio catalog repository

### PR DESCRIPTION
**Pull request by johnbelamaric**
Fixes https://github.com/nephio-project/nephio/issues/392

### CODE REVIEW

**Review by gvbalaji — APPROVED** [review]
/approve

**Comment by efiacor** [comment]
Do we need an area for nephio/core (ie. nephio-controllers, porch-dev, etc) or is that covered by nephio/base?

**Comment by johnbelamaric** [comment]
> Do we need an area for nephio/core (ie. nephio-controllers, porch-dev, etc) or is that covered by nephio/base?

If people think "core" is more evocative, I can go with that.

**Comment by efiacor** [comment]
> > Do we need an area for nephio/core (ie. nephio-controllers, porch-dev, etc) or is that covered by nephio/base?
> 
> If people think "core" is more evocative, I can go with that.

I'm fine with either. Just looking at our current docs might cause some confusion with "base".
https://github.com/nephio-project/docs/blob/main/install-guide/explore-sandbox.md

**Comment by efiacor** [comment]
> > I'm fine with either. Just looking at our current docs might cause some confusion with "base".
> > https://github.com/nephio-project/docs/blob/main/install-guide/explore-sandbox.md
> 
> I'll switch it to "core". I think though ultimately as we re-organize all these for R2, we will update the diagrams.

Agreed. Don't mind me being pedantic. Thanks

**Pull request merged**
